### ISSUE TITLE
Issue with gcc 4.8.4

### ISSUE THREAD

**Issue by vero410** [cmaureir/gravidy#1]
Compilation fails when trying to compile on gcc 4.8.4 with undefined references to ompi and boost::program_options. A workaround is to modify Makefile to add the CXXFLAGS at the end of the command line.

Changing: 
$(CXX) $(CXXFLAGS) $^ -o $@
to:
$(CXX) $^ -o $@ $(CXXFLAGS)

**Comment by cmaureir** [comment]
Are you running a Debian-based Linux OS? (Ubuntu maybe?)

I had experiences  were the FLAGS needed to be at the end of each compiling line.
My OS is running GCC 7.2 hence I have boost using the latest GCC version.

Can you give me more information on your system specs? (OS, boost version, ompi version)
Maybe there is a missing package for boost.

Cheers

**Comment by cmaureir** [comment]
This was an Ubuntu isolated matter, and it's solved 👍
